### ISSUE TITLE
Docbook

### ISSUE THREAD

**Issue by cromerc** [cromnix/artools#3]
Fails to build currently do to missing docbook2x. I am going to compile docbook2x and it's dependencies.

Is it possible to have it not make and install the documentation if docbook2x is not found in the system?

I think this is the only dependency that is stopping me from testing and using buildpkg.

**Comment by udeved** [comment]
I could make it so, but docbook is often required i all kid of packages.
I think you could even get arch binary package installed with pacman -U.

More important would be to sign the repo packages asap so we can start building.

**Comment by cromerc** [comment]
True, if you do a grep of the package repo for "todo" you will notice that I have a lot of packages that don't have documentation because of missing packages such as docbook2x, doxygen, fop, etc.

I will go ahead and sign the packages now and upload the signatures.

**Comment by udeved** [comment]
This would be cool, because chroot only fails due to missing sigs. :)

**Comment by udeved** [comment]
When sigs are in place, I can convert my arch install.

**Comment by cromerc** [comment]
Sigs are in place

**Comment by cromerc** [comment]
Just noticed, the repo sigs are working, however the packages sigs are failing. Looking into the problem now.

**Comment by cromerc** [comment]
Fixed, just creating the .sig files is not enough. I had to re-add all the packages to the repo after the .sig files were made.

**Comment by cromerc** [comment]
I added a bunch of the dependencies for docbook, but there are some more to go which I will try to get built tomorrow afternoon after I get back from the uni.

Are there any other dependencies missing to get the buildpkg and chrooting functionality working? Please let me know and I will try to get them done tomorrow.

**Comment by udeved** [comment]
I think the docbook package was important.
There is a depend on mktorrent, and ruby-kwalify for iso stuff, but we can take it out for the moment.

All other depends are in the packages-vcs, mainly iso related. Probably best to comment out the artools-iso package in the build.

**Comment by cromerc** [comment]
Docbook2x is ready, so going to close this issue.
